# Generated by Django 3.2.6 on 2022-01-04 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prizes', models.CharField(max_length=999)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_title', models.CharField(max_length=200)),
                ('rules', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=100)),
                ('college', models.CharField(max_length=500)),
                ('prizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventdbApp.prize')),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('main_title', models.CharField(max_length=200)),
                ('secondary_title', models.CharField(max_length=200)),
                ('date', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('image1', models.FileField(upload_to='images')),
                ('image2', models.FileField(upload_to='images')),
                ('image3', models.FileField(upload_to='images')),
                ('image4', models.FileField(upload_to='images')),
                ('image5', models.FileField(upload_to='images')),
                ('image6', models.FileField(upload_to='images')),
                ('prizes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventdbApp.prize')),
                ('rules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventdbApp.rules')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EventdbApp.location')),
                ('winners', models.ManyToManyField(blank=True, to='EventdbApp.Winner')),
            ],
        ),
    ]
