# Generated by Django 3.2.6 on 2022-01-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EventdbApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=199)),
                ('education', models.CharField(max_length=299)),
                ('description', models.CharField(max_length=999)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='eventEnded',
            field=models.CharField(default='False', max_length=5),
        ),
        migrations.AddField(
            model_name='events',
            name='eventRegistrationLink',
            field=models.CharField(blank=True, max_length=99, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='main_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='secondary_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
