# Generated by Django 3.2.6 on 2022-01-23 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventdbApp', '0002_auto_20220123_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EventdbApp.speaker'),
        ),
    ]
